//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theodorus2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Left {
            get {
                return ((int)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Top {
            get {
                return ((int)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3*")]
        public global::System.Windows.GridLength EditorHeight {
            get {
                return ((global::System.Windows.GridLength)(this["EditorHeight"]));
            }
            set {
                this["EditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7*")]
        public global::System.Windows.GridLength ResultHeight {
            get {
                return ((global::System.Windows.GridLength)(this["ResultHeight"]));
            }
            set {
                this["ResultHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ResultLimit {
            get {
                return ((int)(this["ResultLimit"]));
            }
            set {
                this["ResultLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLineNumbers {
            get {
                return ((bool)(this["ShowLineNumbers"]));
            }
            set {
                this["ShowLineNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string Font {
            get {
                return ((string)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n    body {\r\n        font-family: \"Consolas\", monospace;\r\n        font-size: 14p" +
            "x;\r\n    }\r\n\r\n    .resultset {\r\n        margin-left: 1em;\r\n        margin-right: " +
            "1em;\r\n        margin-bottom: 1em;\r\n        border-bottom: 2px solid black;\r\n    " +
            "}\r\n\r\n    .query {\r\n        background: #DDD;\r\n        margin: 0 auto;\r\n        b" +
            "order: 1px solid black;\r\n        padding: 4px;\r\n        margin-bottom: 1em;\r\n   " +
            "     white-space: pre;\r\n    }\r\n\r\n    .duration {\r\n        float: right;\r\n       " +
            " margin-top: -2.5em;\r\n        margin-right: 2em;\r\n    }\r\n\r\n    .duration:after {" +
            "\r\n        content: \" ms\";\r\n    }\r\n\r\n    .duration:before {\r\n        content: \"Ex" +
            "ecution time: \";\r\n    }\r\n\r\n    .error {\r\n        color: Red;\r\n    }\r\n\t\t\t\r\n    .e" +
            "rror, .message {\r\n        margin-left: 2em;\r\n        margin-top: 1em;\r\n        m" +
            "argin-bottom: 1em;\r\n    }\r\n\t\t\t\t\t\r\n    table {\r\n        margin-bottom: 1em;\r\n    " +
            "    margin-left: 2em;\r\n        border-collapse: collapse;\r\n        border-style:" +
            " solid;\r\n        border-color: black;\r\n        border-width: 1px;\r\n        clear" +
            ": both;\r\n        width: auto;\r\n    }\r\n\r\n    table tr:nth-child(even) {\r\n        " +
            "background-color: #EEE;\r\n    }\r\n\r\n    table tr:hover {\r\n        background-color" +
            ": #BBB;\r\n    }\r\n\r\n\t\t\t\r\n    table thead, table tfoot {\r\n        border-bottom-sty" +
            "le: solid;\r\n        border-bottom-color: black;\r\n        border-bottom-width: 1p" +
            "x;\r\n        background-color: #CCC;\r\n        font-weight: bold;\r\n    }\r\n\r\n    ta" +
            "ble td {\r\n        border-width: 1px;\r\n        border-left-style: solid;\r\n       " +
            " border-right-style: solid;\r\n        border-left-color: black;\r\n        border-r" +
            "ight-color: black;\r\n        padding-left: 1em;\r\n        padding-right: 1em;\r\n   " +
            "     padding-top: 2px;\r\n        padding-bottom: 2px;\r\n    }\r\n")]
        public string ResultStyle {
            get {
                return ((string)(this["ResultStyle"]));
            }
            set {
                this["ResultStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"binaryguid=True;cache size=4096;datetimeformat=ISO8601;datetimeformatstring=o;datetimekind=Utc;default isolationlevel=ReadCommitted;default timeout=30;failifmissing=False;useutf16encoding=False;flags=Default;foreign keys=True;journal mode=Default;legacy format=False;page size=16384;read only=False;synchronous=Normal;version=3")]
        public string DefaultConnectionString {
            get {
                return ((string)(this["DefaultConnectionString"]));
            }
            set {
                this["DefaultConnectionString"] = value;
            }
        }
    }
}
